vich_uploader:
    db_driver: orm
    storage: flysystem

    metadata:
        type: attribute

    mappings:
       files:
           uri_prefix: '%env(S3_STORAGE_PREFIX)%'
           upload_destination: uploads.storage.aws
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
